// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/classnames/classnames.d.ts
// 送送修改过
declare type ClassValue = string | number | ClassDictionary | ClassArray;

interface ClassDictionary {
    [id: string]: boolean;
}

interface ClassArray extends Array<ClassValue> {
}

interface ClassNamesFn {
    (c1: ClassValue, c2?: ClassValue, c3?: ClassValue, c4?: ClassValue, c5?: ClassValue, c6?: ClassValue, c7?: ClassValue, c8?: ClassValue, c9?: ClassValue): string
}

declare var classNames: ClassNamesFn;

declare module "classnames" {
    export = classNames
}
